<link href="<?php echo base_url(); ?>assets/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="<?php echo base_url(); ?>assets/js/jquery-1.12.4.js"></script>
<script src="<?php echo base_url(); ?>assets/js/jquery-ui.js"></script>
<script>
$(function(){ 
    $("#tanggal").datepicker({
        showOn: "button",
        buttonImage: "<?php echo base_url(); ?>img/Kalender.png",
        buttonImageOnly: true,
        buttonText: "Select date",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy'
    });     
    
});
</script>
<div class="row">                            
    <div class="col-md-12"> 
        <form class="eventInsForm" method="post" target="_self" name="formku" 
            id="formku" action="<?php echo base_url('index.php/BackOffice/save_sales_order'); ?>">
            <div class="row">
                <div class="col-md-12 col-sm-12"><h4>Input Sales Order</h4></div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="alert alert-danger display-hide">
                        <button class="close" data-close="alert"></button>
                        <span id="message">&nbsp;</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5 col-sm-12">                                                        
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            Tanggal <font color="#f00">*</font>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <input type="text" id="tanggal" name="tanggal" 
                                class="form-control myline input-small" style="margin-bottom:5px; float:left" 
                                value="<?php echo date('d-m-Y'); ?>">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            Nomor Sales Order <font color="#f00">*</font>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <input type="text" id="no_sales_order" name="no_sales_order" 
                                class="form-control myline" style="margin-bottom:5px;" 
                                value="Auto generated by system" readonly="readonly">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            Customer<font color="#f00">*</font>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <select id="m_customer_id" name="m_customer_id" class="form-control myline select2me" 
                                data-placeholder="Pilih customer..." style="margin-bottom:5px">
                                <option value=""></option>
                                <?php
                                    foreach ($list_customer as $row){
                                        echo '<option value="'.$row->id.'">'.$row->nama_customer.'</option>';
                                    }
                                ?>
                            </select>
                        </div>
                    </div>                    
                    <div class="row"><p>&nbsp;</p></div>
                    <div class="row">
                        <div class="col-md-4 col-sm-12">&nbsp;</div>
                        <div class="col-md-8 col-sm-12">
                            <input type="button" onClick="simpandata();" name="btnSave" 
                                value="Tambah Produk" class="btn btn-primary" id="btnSave">
                            <a href="<?php echo base_url('index.php/BackOffice/sales_order'); ?>" class="btn btn-default">
                                Batal</a>
                        </div>
                    </div>
                </div>                
            </div>
        </form>
    </div>
</div>  

<script>    
function simpandata(){		
    if($.trim($("#tanggal").val()) == ""){
        $('#message').html("Tanggal harus diisi, tidak boleh kosong!");
        $('.alert-danger').show();   
    }else if($.trim($("#m_customer_id").val()) == ""){
        $('#message').html("Silahkan pilih customer!");
        $('.alert-danger').show();    
    }else{
        $('#btnSave').attr("disabled", true);        
        $('#formku').submit();
    };
};
</script>
        